### ISSUE TITLE
error

### ISSUE THREAD

**Issue by dok441** [Alf21/ttt2-role_siki#9] opened 2019-07-07 23:27 UTC
[ERROR] addons/ttt2-role_siki-master/gamemodes/terrortown/entities/weapons/weapon_ttt2_sidekickdeagle.lua:206: attempt to perform arithmetic on local 'timeLeft' (a nil value)
  1. func - addons/ttt2-role_siki-master/gamemodes/terrortown/entities/weapons/weapon_ttt2_sidekickdeagle.lua:206
   2. unknown - lua/includes/extensions/net.lua:32

**Comment by dok441** [comment] 2019-07-07 23:52
[ERROR] addons/ttt2-role_siki-master/gamemodes/terrortown/entities/weapons/weapon_ttt2_sidekickdeagle.lua:156: attempt to call method 'HasWeapon' (a nil value)
  1. fn - addons/ttt2-role_siki-master/gamemodes/terrortown/entities/weapons/weapon_ttt2_sidekickdeagle.lua:156
   2. unknown - addons/ulib-master/lua/ulib/shared/hook.lua:109

**Comment by dok441** [comment] 2019-07-08 14:26
https://github.com/Alf21/TTT2/issues/355 Also because of this role there is this problem, I understand because of 2 errors.

**Comment by lebroomer** [comment] 2019-07-08 17:36
Yeah, this errors are producing your described problem in #355. But I have honestly no clue, how this can happen. Both errors are quite impossible, because there are checks beforehand. This could maybe be caused by another addon which interferes here. Could you test, if the same behaviour is occuring with only TTT2+ the Roles installed?

**Comment by lebroomer** [comment] 2019-07-08 18:00
The second error and thus the false alives should be fixed now with the newest commit.

**Comment by lebroomer** [comment] 2019-07-08 18:05
So, I added a fallback solution for the first error. Did the Jackal killed someone just in the second the timer was running out? Because that could have produced the error as a superrare edge case, which should be fixed now.

**Closed as completed** 2019-07-09 01:13 UTC
Labels: needs info
